site_name: 주진현의 스냅샷
site_url: https://jinhyun.blog/
site_author: 주진현
site_description: >-
  개발자로써 살아가는 지혜

# Repository
repo_name: harryjhin/blog
repo_url: https://github.com/harryjhin/blog

# Configuration
theme:
  language: ko
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    - content.action.edit
    - content.action.view
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    # - navigation.path # Sponsors only
    # - navigation.prune # Sponsors only
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Nanum Gothic
    code: JetBrains Mono
  favicon: images/logo.png
  icon:
    logo: material/library

# Plugins
plugins:
  - search

# Customization
extra:
  analytics:
    provider: google
    property: fab73bf4df2f9ba92
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/harryjhin

# Extensions
markdown_extensions:
  # 주의사항 (https://squidfunk.github.io/mkdocs-material/reference/admonitions/)
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - abbr
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  # https://squidfunk.github.io/mkdocs-material/reference/lists/
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.tilde

# Page tree
nav:
  - 프로그래밍:
      - 컴파일러와 인터프리터: 프로그래밍/컴파일러와_인터프리터.md
  - 깃:
      - 개요: git/overview.md
      - 설정: git/setup.md
      - 리포지토리 생성: git/init.md
      - 커밋: git/commit.md
      - 변경 사항 되돌리기: git/checkout.md
      - 스테이지 취소하기: git/stage-reset.md
      - 커밋 되돌리기: git/commit-reset.md
  - 코틀린:
      - Overview: kotlin/overview.md
      - 기본:
          - 진입점: kotlin/basic/entry-point.md
          # - 주석: kotlin/basic/comments.md
          # - 함수: kotlin/basic/functions.md
          # - 변수: kotlin/basic/variables.md
          # - 클래스: kotlin/basic/classes.md
          # - 조건문: kotlin/basic/conditional-expression.md
          # - 반복문: kotlin/basic/loop.md
          # - 범위: kotlin/basic/range.md
          # - 컬렉션: kotlin/basic/collections.md
      - 개념:
          - 원시 데이터 타입: kotlin/concepts/primitive-data-type.md
      - 기타:
          - Kotlin을 위한 editorconfig 구성: kotlin/기타/editorconfig.md
  - 안드로이드:
      - Overview: android/overview.md
      - 고급:
          - 로깅: android/advanced/logging.md
      - Hilt:
          - 의존성 주입: android/hilt/overview.md
          - 의존성 주입 with Hilt: android/hilt/setup.md
          - WorkManager: android/hilt/workmanager.md
          - 싱글톤: android/hilt/singleton.md
      - Jetpack:
          - 아키텍처:
              - App Startup: android/jetpack/architecture/app-startup.md
          - Data Layer:
              - Datastore:
                  - Proto Datastore: android/jetpack/data/datastore/proto-datastore.md
              - Database(ROOM):
                  - Overview: android/jetpack/data/room/overview.md
              - WorkManager:
                  - Overview: android/jetpack/data/workmanager/overview.md
          - Compose:
              - 개요: android/jetpack/compose/overview.md
              - 기본:
                  - 상태 관리: android/jetpack/compose/basic/status.md
                  - 수명 주기: android/jetpack/compose/basic/lifecycle.md
                  - 부수 효과: android/jetpack/compose/basic/side-effects.md
                  - 단계: android/jetpack/compose/basic/phases.md
              # - Material:
              # - Overview: android/jetpack/compose/material/overview.md
              # - Component:
              # - Button: android/jetpack/compose/material/button.md
  - JPA:
      - jpa/jpa-overview.md
      - 기본:
          - 영속성 컨텍스트: jpa/basic/persistence-context.md
          - 엔티티 매핑: jpa/basic/entity-mapping.md
          - 연관관계: jpa/basic/relation.md
          - 프록시: jpa/basic/proxy.md
  # - Spring Boot:
  #     - Overview: spring-boot/overview.md
  # - Mac:
  #     - Overview: mac/overview.md
  # - Alfred: mac/alfred.md
  # - MacPorts: mac/macports.md
  # - Homebrew: mac/homebrew.md
  # - zsh:
  # - Homebrew Installation: mac/zsh/homebrew-installation.md
  # - iTerm2 Installation: mac/zsh/iterm2-installation.md
  # - Oh My Posh Installation: mac/zsh/oh-my-posh-installation.md
  - Windows:
      - Overview: windows/overview.md
      - Powertoys:
          - Overview: windows/powertoys/overview.md
          - Installation: windows/powertoys/installation.md
      - Powershell:
          - Overview: windows/powershell/overview.md
      - Winget:
          - Overview: windows/winget/overview.md
          - Installation: windows/winget/installation.md
      # - WSL:
      #     - Overview: windows/wsl/overview.md
      #     - Installation: windows/wsl/installation.md
      #     - Homebrew Installation: windows/wsl/homebrew-installation.md
      #     - Oh My Posh Installation: windows/wsl/oh-my-posh-installation.md
  - Material Mkdocs:
      - Overview: material-mkdocs/overview.md
      - Buttons: material-mkdocs/buttons.md
      # - Icon, Imoji: material-mkdocs/icon-imoji.md
  - 산업기능요원:
      - 산업기능요원/index.md
      - 산업기능요원/군사교육소집.md
      - 산업기능요원/휴가와_병가.md
