site_name: 주진현의 스냅샷
site_url: https://jinhyun.blog/
site_author: 주진현
site_description: >-
  나의 학습 기록 공유

# Repository
repo_name: harryjhin/blog
repo_url: https://github.com/harryjhin/blog

# Configuration
theme:
  language: kr
  name: material
  custom_dir: overrides
  features:
    # - announce.dismiss
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Nanum Gothic
    code: JetBrains Mono
  favicon: images/logo.png
  icon:
    logo: material/library

# Plugins
plugins:
  - search

# Customization
extra:
  analytics:
    provider: google
    property: fab73bf4df2f9ba92
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/harryjhin

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Kotlin:
      - Overview: kotlin/overview.md
      - Basic Syntax:
          - 주석(comments): kotlin/basic-syntax/comments.md
          - 변수(val, var): kotlin/basic-syntax/variable.md
  - Git:
      - Overview: git/overview.md
  - Android:
      - Overview: android/overview.md
      - Hilt:
          - Overview: android/hilt/overview.md
          - Setup: android/hilt/setup.md
      - Jetpack Compose:
          - Overview: android/jetpack-compose/overview.md
          - Material:
              - Overview: android/jetpack-compose/material/overview.md
              - Component:
                  - Button: android/jetpack-compose/material/button.md
  - Spring Boot:
      - Overview: spring-boot/overview.md
  - Mac:
      - Overview: mac/overview.md
      - Alfred: mac/alfred.md
      - zsh:
          - Homebrew Installation: mac/zsh/homebrew-installation.md
          - iTerm2 Installation: mac/zsh/iterm2-installation.md
          - Oh My Posh Installation: mac/zsh/oh-my-posh-installation.md
  - Windows:
      - Overview: windows/overview.md
      - Powertoys: windows/powertoys.md
      - Powershell:
          - Overview: windows/powershell/overview.md
      - Winget:
          - Overview: windows/winget/overview.md
          - Installation: windows/winget/installation.md
      - WSL:
          - Overview: windows/wsl/overview.md
          - Installation: windows/wsl/installation.md
          - Homebrew Installation: windows/wsl/homebrew-installation.md
          - Oh My Posh Installation: windows/wsl/oh-my-posh-installation.md
  - Material Mkdocs:
      - Overview: material-mkdocs/overview.md
      - Icon, Imoji: material-mkdocs/icon-imoji.md
